galaxy_info:
  role_name: user_management
  description: Настройка IPERF3 и создание пользователей.
  author: Magomedov Magomed
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
